apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: aks
  labels:
    app: dotnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: aksss.azurecr.io/acrimage:1.0.0
        ports:
        - containerPort: 5000
