# network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dotnet-egress
  namespace: aks
spec:
  podSelector:
    matchLabels:
      app: dotnet-app
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0 # Allow all egress traffic, update CIDR based on your requirements
